FROM rocm/pytorch:rocm7.2.4_ubuntu22.04_py3.10_pytorch_release_2.10.0

RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends ca-certificates curl gnupg \
  ca-certificates \
  sudo libelf1 libnuma-dev libssl-dev \
  pkg-config \
  build-essential \
  git \
  file less \
  ninja-build \
  clang \
  libfile-which-perl liburi-perl libtbb-dev && \
  apt-get clean && \
  rm -rf /var/lib/apt/lists/*

ARG CMAKE_VERSION=4.4.3
RUN curl -fsSL "https://cmake.org/files/v4.4/cmake-${CMAKE_VERSION}-linux-x86_64.tar.gz" \
      -o /tmp/cmake.tar.gz && \
  tar -xzf /tmp/cmake.tar.gz --strip-components=1 -C /usr/local && \
  rm /tmp/cmake.tar.gz

RUN pip install --upgrade pip twine auditwheel patchelf
