hunter_config(abseil VERSION ${HUNTER_abseil_VERSION}
  CONFIGURATION_TYPES Release
  CMAKE_ARGS
    CMAKE_CXX_STANDARD=20
    CMAKE_POSITION_INDEPENDENT_CODE=ON
)

hunter_config(gflags VERSION ${HUNTER_gflags_VERSION}
  CONFIGURATION_TYPES Release
  CMAKE_ARGS
    CMAKE_POLICY_VERSION_MINIMUM=3.10
    CMAKE_POSITION_INDEPENDENT_CODE=ON
)

hunter_config(RapidJSON VERSION ${HUNTER_RapidJSON_VERSION}
  CONFIGURATION_TYPES Release
  CMAKE_ARGS
    CMAKE_POLICY_VERSION_MINIMUM=3.10
    CMAKE_POSITION_INDEPENDENT_CODE=ON
)
